### ISSUE TITLE
Use ScriptInjector instead of putting hopscotch-0.1.js in gwt.xml module file

### ISSUE THREAD

**Issue by timeu** [eemi2010/gwt-tour#1]
Putting script files in gwt.xml module files won't work when using an xsiframe linker (SuperDevMode).

**Comment by eliovir** [comment]
I confirm that I can't use gwt-tour, running `mvn gwt:compile` on my project returns:

```
[INFO]    Invoking Linker Cross-Site-Iframe
[INFO]       [ERROR] The Cross-Site-Iframe linker does not support <script> tags in the gwt.xml files, but the gwt.xml file (or the gwt.xml files which it includes) contains the following script tags: 
[INFO] hopscotch-0.1.js
[INFO] In order for your application to run correctly, you will need to include these tags in your host page directly. In order to avoid this error, you will need to remove the script tags from the gwt.xml file, or add this property to the gwt.xml file: <set-configuration-property name='xsiframe.failIfScriptTag' value='FALSE'/>
```

**Comment by patou** [comment]
Hello eliovir,

In the trunk version, the ScriptLoader is commited.
Just Load the GwtTourScriptLoader module xml instead of the GwtTour one.
And call GwtTour.load() for loading the script. GwtTour.isLoading() allow to wait until the script is loading.

**Comment by eliovir** [comment]
Hello patou,

thanks for your reply, but I do not manage to make it work.

I added those lines into `pom.xml`:

```
               <dependency>
                       <groupId>com.eemi.gwt</groupId>
                       <artifactId>tour</artifactId>
                       <version>1.0-SNAPSHOT</version>
               </dependency>
<!-- ... -->
        <repositories>
               <repository>
                       <id>gwttour-mvn-repo</id>
                       <url>https://raw.github.com/kerbymart/gwt-tour/mvn-repo/</url>
                       <snapshots>
                               <enabled>true</enabled>
                               <updatePolicy>always</updatePolicy>
                       </snapshots>
               </repository>
       </repositories>
```

Instead of `<inherits name='com.eemi.gwt.tour.GwtTour'/>` ([src/main/java/.../GwtTour.gwt.xml](https://github.com/eemi2010/gwt-tour/blob/master/src/main/java/com/eemi/gwt/tour/GwtTour.gwt.xml)), I added the GwtTourScriptLoader module in `.gwt.xml`:
([/src/main/resources/../GwtTourScriptLoader.gwt.xml](https://github.com/eemi2010/gwt-tour/blob/master/src/main/resources/com/eemi/gwt/tour/GwtTourScriptLoader.gwt.xml))
```
       <inherits name='com.eemi.gwt.tour.GwtTourScriptLoader'/>
```
and run `mvn gwt:compile` with the other failure:

`GWT Module com.eemi.gwt.tour.GwtTourScriptLoader not found in project sources or resources.`

This file in not in the .jar. Is there another SNAPSHOT?

I tried to use the master branch, but got the same problem, the other module is not in the .jar:

```
git clone https://github.com/eemi2010/gwt-tour
cd gwt-tour
mvn install
cd ~/myproject
mvn gwt:compile
```

I succeed to compile without error, changing `pom.xml`. This is the `git diff` output:
```
diff --git a/pom.xml b/pom.xml
index dbae200..4e4546d 100644
--- a/pom.xml
+++ b/pom.xml
@@ -43,10 +43,11 @@
 
        <build>
 
+               <sourceDirectory>src/main/java</sourceDirectory>
                <!-- Include .gwt.xml -->
                <resources>
                        <resource>
-                               <directory>src/main/java</directory>
+                               <directory>src/main/resources</directory>
                        </resource>
                </resources>
```

I did not test if it works, I do not have HTML element with `id`.
Now, I had to know how to attach the steps to `@UiField` elements.

**Comment by eemi2010** [comment]
Note that we will move this project to the ahome homespace. We also have a small surprise for  the net GWT. Tour :)

**Comment by eemi2010** [comment]
The new library is now located here https://oss.sonatype.org/content/repositories/snapshots/com/ahome-it/gwt-tour/. We also added support for intro.js
Enjoy :)
